DL-2663 - Updated dependencies
hmrc/cc-eligibility pull request #114
Opened 2020-01-22 13:45 UTC by alijy

# DL-2663 - Updated dependencies

**New feature**

Updated dependencies

## Checklist

 - [x]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
 - [x]  I've executed the acceptance test pack locally to ensure there are no functional regressions
 - [x]  I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
 - [x]  I've run a dependency check to ensure all dependencies are up to date

2020-01-27 16:56 UTC, benryan1790 requested changes
Following libraries/plugins can be upgraded further:

- com.kenshoo:metrics-play
- org.mockito:mockito-core
- org.scalatest:scalatest
- org.scalatestplus.play:scalatestplus-play
- org.scoverage:sbt-scoverage

2020-01-28 14:26 UTC, alijy commented
> Following libraries/plugins can be upgraded further:
> 
> * com.kenshoo:metrics-play
> * org.mockito:mockito-core
> * org.scalatest:scalatest
> * org.scalatestplus.play:scalatestplus-play
> * org.scoverage:sbt-scoverage

Done. (Only scoverage needed an upgrade)

2020-02-04 16:49 UTC, stephen-oppong-beduh commented on buid.sbt
> +import uk.gov.hmrc.DefaultBuildSettings.targetJvm
The build.sbt file is named ```buid.sbt```

2020-02-04 16:54 UTC, stephen-oppong-beduh commented on project/AppDependencies.scala
> +    typesafe %% "play-json-joda" % "2.7.4"
```play-json-joda``` can go up to 2.8.1

2020-02-05 12:15 UTC, alijy commented on project/AppDependencies.scala
> +    typesafe %% "play-json-joda" % "2.7.4"
Done.

2020-02-05 15:29 UTC, stephen-oppong-beduh approved these changes

2020-02-05 15:58 UTC, merged